### ISSUE TITLE
[BUG] Folder unwrap causes crashing

### ISSUE THREAD

**Issue by hackgrid** [T0biasCZe/AdbFileManager#28]
**Describe the bug**
I want to transfer my Samsung Galaxy Tab S4 to my PC.
I choose "Unwrap folders on copy" and transferred all folders at once.

**Unhandled exception log**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AdbFileManager.Functions.isFolder(String path, Boolean old_android) in C:\Users\user\source\repos\AdbFileManager\AdbFileManager\Form1.cs:line 664
   at AdbFileManager.Form1.android2pc_Click(Object sender, EventArgs e) in C:\Users\user\source\repos\AdbFileManager\AdbFileManager\Form1.cs:line 232
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Private.CoreLib.dll
----------------------------------------
AdbFileManager
    Assembly Version: 1.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\AdbFileManager.dll
----------------------------------------
System.Runtime
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Drawing.Common.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Runtime.InteropServices.dll
----------------------------------------
System.Threading
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Collections.dll
----------------------------------------
System.Data.Common
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Data.Common.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.ComponentModel.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Private.Xml.dll
----------------------------------------
System.Console
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Console.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\Accessibility.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Configuration.ConfigurationManager.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.ObjectModel.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Private.Uri.dll
----------------------------------------
System.Security.Cryptography
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Security.Cryptography.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Collections.Concurrent.dll
----------------------------------------
System.Memory
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Memory.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Net.WebClient.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Text.Encoding.Extensions.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Xml.XmlSerializer.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 7.0.4.0
    Location: C:\Users\user\Downloads\adb.file.manager\Microsoft.WindowsAPICodePack.Shell.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Core
    Assembly Version: 7.0.4.0
    Location: C:\Users\user\Downloads\adb.file.manager\Microsoft.WindowsAPICodePack.Core.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Runtime.Loader.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Drawing.dll
----------------------------------------
AdbFileManager.resources
    Assembly Version: 1.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\en\AdbFileManager.resources.dll
----------------------------------------
System.Linq
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Linq.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Runtime.Numerics.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Threading.ThreadPool.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Collections.NonGeneric.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\Microsoft.Win32.Registry.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Diagnostics.Process.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Text.RegularExpressions.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.IO.MemoryMappedFiles.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 8.0.0.0
    Location: C:\Users\user\Downloads\adb.file.manager\System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************

**To Reproduce**
-

**Expected behavior**
To copy without error.

**Screenshots**
![grafik](https://github.com/T0biasCZe/AdbFileManager/assets/54060/eb22c7d3-fb77-4212-9ae7-81754ad07559)

**Desktop (please complete the following information):**
Windows 10

**Additional context**
-

**Comment by nadr21a21** [comment]
I'm having the same problem here, did you find a solution? @T0biasCZe 
@hackgrid

**Comment by hackgrid** [comment]
No, I gave up...

**Comment by nadr21a21** [comment]
> No, I gave up...

Do you have an alternative with the same I mean software with the same working system ? @hackgrid

**Comment by yw-tsikin** [comment]
I also encountered this bug, but what I tried is unchecking the unwrap folders on Copy then there it copied. (What's the purpose of Unwrapping the Folders on copy anyway?)
But is there any fix yet?

**Comment by T0biasCZe** [comment]
> (What's the purpose of Unwrapping the Folders on copy anyway?)4

smoother progressbar, since instead of copying the whole folder as 1 item, it unwraps them as invidual files

**Comment by SELEKCJONER** [comment]
is it possible to disable that
i have about 13k folders each has a sub folder with files they take about 10 GB in total
unwrapping all of that takes too much time
so much that i never was able to actually copy my files i always were stuck at unwrapping

**Comment by SELEKCJONER** [comment]
using adb pull directly confirms that unwrapping is extremly inefficient
adb pull for whole folder on my phone started copying and finished in less time than i wasted waiting for folder unwrapping

**Comment by hackgrid** [comment]
Just use ADB-Explorer guys, it is way better!
https://github.com/Alex4SSB/ADB-Explorer

**Comment by T0biasCZe** [comment]
> is it possible to disable that
![image](https://github.com/user-attachments/assets/47c13287-8b9c-42a5-b1d3-47311fd4547d)

**Comment by T0biasCZe** [comment]
> > (What's the purpose of Unwrapping the Folders on copy anyway?)

> smoother progressbar, since instead of copying the whole folder as 1 item, it unwraps them as individual files, so they then get individually copied and the progressbar is smoother



https://github.com/user-attachments/assets/01c9cc40-4c40-4a01-8eaf-a329f321ad64

**Comment by yw-tsikin** [comment]
> > > (What's the purpose of Unwrapping the Folders on copy anyway?)
> 
> > smoother progressbar, since instead of copying the whole folder as 1 item, it unwraps them as individual files, so they then get individually copied and the progressbar is smoother
> 
>  Unwrap.on.vs.Off.mp4

this is actually much better and faster copying. It may freeze but dont worry because it's still copying on background.

**Comment by incom2** [comment]
This is still happening. And it's due at least one of the selected folders, whatever level its placed, is empty. The program is probably trying to list the files inside, gets nothing, the index crashes. As soon as you select only folders with content inside, this bug is not happening. But, Android is plagued with obscure empty folders, so... fix it, please. Should be really easy.

**Comment by hackgrid** [comment]
Why do you insist using this program, just use ADB-Explorer it works without any issue!
AdbFileManager has so many strange little problems and bugs, its not worth wasting your time with it.

**Comment by incom2** [comment]
Tried again, different phone (Pixel 8 Pro with latest Android version) on Windows 11 Pro using latest beta of the program, and crashes anytime the copy selection includes an empty folder (meaning, you go inside and only see 'No files found -- 0 KiB -- 01/01/1970'). If I would to guess, I think the program when unfolding those empty folders, is trying to copy that 'No files found' item and since it doesn't exists, the program crashes.

Aaaand, yes. I could use any other ADB program, but this one is small and simple enough and I'm only using it from time to time. Anyway, good to know there are other alternatives!

**Comment by incom2** [comment]
That's pretty cool, thanks for your job!
Will keep looking for the update.

**Comment by T0biasCZe** [comment]
closing issue since the original problem with unwrapping was solved, if any more problems arise feel free to open a new issue
